
// This file was auto-generated by ML.NET Model Builder. 

using TextClassifierConsoleApp;

// Create single instance of sample data from first line of dataset for model input
TextClassifier.ModelInput sampleData = new TextClassifier.ModelInput()
{
    Title = @"People's Choice Awards 2018: The best red carpet looks",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Real with predicted Real from sample data...\n\n");


Console.WriteLine($"Real: {1F}");
Console.WriteLine($"Title: {@"People's Choice Awards 2018: The best red carpet looks"}");


var sortedScoresWithLabel = TextClassifier.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

